### ISSUE TITLE
"matlab/gtsam_examples/IMUKittiExampleGPS" fails to run!

### ISSUE THREAD

**Issue by solution3000** [jlblancoc/factor-graphs-course#1]
https://user-images.githubusercontent.com/20204121/93060127-4b807280-f6a4-11ea-9ea8-292e822707b6.png

**Comment by jlblancoc** [comment]
Hmm... sorry but this may be a bug of the [upstream project](https://github.com/borglab/gtsam).

If it still fails when you build the latest ("develop" branch) version of gtsam and its matlab wrapper, please, file an issue against the upstream project.
